name: CI/CD Pipeline for Angular

on:
  push:
    branches:
      - main

jobs:
  Build_and_Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm install
      - name: Build Angular Project
        run: npm run build

  Build_Docker_Image:
    needs: Build_and_Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
      - name: Build Docker Image
        run: docker build -t nithyanandnadar/angular .
      - name: Publish image to docker hub
        run: docker push nithyanandnadar/angular:latest

  Deploy_to_Production:
    needs: Build_Docker_Image
    runs-on: self-hosted
    steps:
      - name: Pull Image from docker hub
        run: docker pull nithyanandnadar/angular:latest
      - name: Remove Old Container
        run: docker rm -f angular-container || true
      - name: Run Docker Container
        run: docker run -d -p 70:70 --name angular-container nithyanandnadar/angular